pdu:
  ip: 10.150.1.78
  voltage_oid: 1.3.6.1.4.1.42578.1.2.2.0
  energy_oid: 1.3.6.1.4.1.42578.1.2.5.0
  servers:
    - name: compute1
      current_oid: 1.3.6.1.4.1.42578.1.3.2.3.0
    - name: compute2
      current_oid: 1.3.6.1.4.1.42578.1.3.4.3.0
